notatki/urls.py
from django.urls import path

from notatki import views

app_name = 'notatki'
urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),

    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

notatki_projektDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notatki/', include('notatki.urls', namespace='notatki'))
]

notatki/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Opublikowany')
    )
    PRIORITY_CHOICES = (
        (0, "Wazne"),
        (1, "Standard"),
    )

    title = models.CharField(max_length=250)
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=1)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notatki_posts')
    # text = models.TextField(default="tekst")
    body = models.TextField(default="Tutaj wpisz tekst")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='published')


    class Meta:
        ordering = ('priority',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('notatki:post_detail', args=[self.publish.year,
                                                    self.publish.strftime('%m'),
                                                    self.publish.strftime('%d'),
                                                    self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Notatka zaktualizowana przez {self.name}"

notatki/forms.py
from django import forms
from django.forms.utils import ErrorList

from notatki.models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('priority', 'title', 'slug', 'body',)

notatki/views.py
from django.contrib.auth.models import User
from django.utils import timezone

from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from django.views.generic.edit import FormView

from notatki.models import Post, Comment
from . import models
from .forms import CommentForm, PostForm
from taggit.models import Tag


# Create your views here.
def post_list(request):
    posts = Post.published.all()
    return render(request, "notatki/post/list.html", context={"posts": posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3  # ile elementow ma byc na jednej stronie
    template_name = "notatki/post/list.html"


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, slug=slug, status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
    comment_form = CommentForm()
    return render(request, 'notatki/post/detail.html',
                  context={"post": post, "comments": comments, "comment_form": comment_form})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.priority = request.POST.get('priority')
            post.save()

            return redirect('/notatki', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'notatki/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('/notatki', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'notatki/post_edit.html', {'form': form})

notatki/templates/notatki/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"><link href="style.css">
</head>
<body>
    <div>
        <a href="{% url 'notatki:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    </div>
    <div>
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Brudnopis</h2>
        <textarea  placeholder="Napisz tutaj:" cols="50" rows="30"></textarea>
    </div>
    {% url 'notatki:post_list' as posty %}
    {% if request.path == posty %}
        <button type="button" class="btn btn-outline-secondary btn-lg" style="margin-top: 20px"><a class="link-underline link-underline-opacity-0 page-link" href="post/new" >Dodaj post</a> </button>
    {% endif %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

notatki/templates/notatki/pagination.html
<ul class="pagination">

        {% if page.has_previous %}
            <li class="page-item"><a class="link-underline link-underline-opacity-0 page-link" href="?page={{ page.previous_page_number }}">Poprzednia</a></li>
        {% else %}
            <li class="page-item disabled"><span class="link-underline link-underline-opacity-0 page-link">Poprzednia</span></li>
        {% endif %}

    {% if page.has_next %}
        <li class="page-item"><a class="link-underline link-underline-opacity-0 page-link" href="?page={{ page.next_page_number }}">Następna</a></li>
    {% else %}
        <li class="page-item disabled"><span class="link-underline link-underline-opacity-0 page-link">Następna</span></li>
    {%endif %}

</ul>

notatki/templates/notatki/post/detail.html
{% extends "notatki/base.html" %}
{% block title %}{{ post.title }} {% endblock %}
{% block content %}

    {% if post.priority == 0 %}
        <h1 class = "link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">{{ post.title }}</h1>
    {% elif post.priority == 1 %}
        <h1 class = "link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">{{ post.title }}</h1>

    {% endif %}

     <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}

        <p>{{ post.text|linebreaks }}</p>
    </div>

     <p class="date">
     Opublikowany {{ post.publish }} przez {{ post.author }}
     </p>  <a class="btn btn-default" href="{% url 'notatki:post_edit' pk=post.pk %}"><button class="btn btn-outline-secondary">Edytuj notatkę</button></a>
     {{ post.body|linebreaks }}

    {% for comment in comments %}
        <div class="comment">
        <p class="info">
            Notatka została zaktualizowana w dniu {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
        </div>
    {% empty %}

    {% endfor %}
    <hr>
    <div style="margin-top: 50px">
    <h2>Dodaj treść do notatki</h2>
    <form action="" method="post" class="bg-dark">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Zapisz"></p>
    </form>
</div>
{% endblock %}

notatki/templates/notatki/post/list.html
{% extends "notatki/base.html" %}
{% block title %}Moje notatki{% endblock %}
{% block content %}
 <h1 style="padding-top: 20px">Moje notatki</h1>
 {% for post in posts %}
 <h2>
 <a class="link-underline link-underline-opacity-0" href="{{ post.get_absolute_url }}">
 {% if post.priority == 0 %}
     <span class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">{{ post.title }}</span>
 {% elif post.priority == 1 %}
    <span class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">{{ post.title }}</span>
 {% endif %}
 </a></h2>

 <p class="date">
 Opublikowany {{ post.publish }} przez {{ post.author }}
 </p>
 {{ post.body|truncatewords:30|linebreaks }}
 {% endfor %}
       {% include "notatki/pagination.html" with page=page_obj %}

{% endblock %}